site_name: mecode_viewer
site_description: Simple GCode Viewer
site_author: Rodrigo Telles
site_url: https://rtellez700.github.io/mecode_viewer/
repo_name: rtellez700/mecode_viewer
repo_url: https://github.com/rtellez700/mecode_viewer/
edit_uri: ""
copyright: 'Copyright &copy; 2022-present'

docs_dir: docs
site_dir: site
theme:
  name: material
  # custom_dir: docs/.overrides
  language: en
  # favicon: assets/images/logo.svg
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/printer-3d-nozzle
    annotation: material/arrow-right-circle
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home:
    - About: index.md
    - About:
      - Release Notes: release-notes.md
      - Contributing: contributing.md
      - License: license.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [mecode]
          options:
            docstring_style: google
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  version:
    provider: mike